CREATE TABLE "actividad_seguimiento" (
	"id"	VARCHAR(255) PRIMARY KEY,
	"project"	VARCHAR(255),
	"beneficiario"	VARCHAR(255),
	"operario"	VARCHAR(255),
	"numero_de_visita"	INT,
	"meta_1"	INT,
	"meta_2"	INT,
	"meta_3"	INT,
	"meta_4"	INT,
	"meta_5"	INT,
	"meta_6"	INT,
	"meta_7"	INT,
	"meta_8"	INT,
	"meta_9"	INT,
	"tipo_de_visita"	INT,
	"direccion"	VARCHAR(255),
	"plan_de_inversiones"	INT,
	"observaciones"	VARCHAR(255),
	"seguimiento_al_desembolso"	INT,
	"alerta_de_seguimiento"	INT,
	"otra_alerta"	VARCHAR(255)
);
CREATE TABLE "plan_de_seguimiento" (
	"id"	VARCHAR(255) PRIMARY KEY,
	"project"	VARCHAR(255),
	"payeeDocument"	VARCHAR(255),
	"operator"	VARCHAR(255),
	"numero_de_visitas"	INT,
	"numero_realizadas"	INT,
	"meta_1"	VARCHAR(255),
	"inicio_1"	VARCHAR(255),
	"final_1"	VARCHAR(255),
	"meta_2"	VARCHAR(255),
	"inicio_2"	VARCHAR(255),
	"final_2"	VARCHAR(255),
	"meta_3"	VARCHAR(255),
	"inicio_3"	VARCHAR(255),
	"final_3"	VARCHAR(255),
	"meta_4"	VARCHAR(255),
	"inicio_4"	VARCHAR(255),
	"final_4"	VARCHAR(255),
	"meta_5"	VARCHAR(255),
	"inicio_5"	VARCHAR(255),
	"final_5"	VARCHAR(255),
	"meta_6"	VARCHAR(255),
	"inicio_6"	VARCHAR(255),
	"final_6"	VARCHAR(255),
	"meta_7"	VARCHAR(255),
	"inicio_7"	VARCHAR(255),
	"final_7"	VARCHAR(255),
	"meta_8"	VARCHAR(255),
	"inicio_8"	VARCHAR(255),
	"final_8"	VARCHAR(255),
	"meta_9"	VARCHAR(255),
	"inicio_9"	VARCHAR(255),
	"final_9"	VARCHAR(255)
);
CREATE TABLE "beneficiario_proyectos" (
	"id"	VARCHAR(255) PRIMARY KEY,
	"project"	VARCHAR(255),
	"operator"	VARCHAR(255),
	"payeeDocument"	VARCHAR(255),
	"date"	VARCHAR(255),
	"status"	INT,
	"plan_de_formacion"	INT,
	"plan_de_implementacion"	INT,
	"plan_de_seguimiento"	INT,
	"concluido_formacion"	INT,
	"concluido_implementacion"	INT,
	"concluido_seguimiento"	INT,
	"monitoreo"	INT,
	"etapa_del_proceso"	INT
);
CREATE TABLE "actividad_implementacion" (
	"id"	VARCHAR(255) PRIMARY KEY,
	"project"	VARCHAR(255),
	"beneficiario"	VARCHAR(255),
	"operario"	VARCHAR(255),
	"numero_de_visita"	INT,
	"meta_1"	INT,
	"meta_2"	INT,
	"meta_3"	INT,
	"meta_4"	INT,
	"meta_5"	INT,
	"meta_6"	INT,
	"meta_7"	INT,
	"meta_8"	INT,
	"meta_9"	INT,
	"tipo_de_visita"	INT,
	"direccion"	VARCHAR(255),
	"plan_de_inversiones"	INT,
	"observaciones"	VARCHAR(255),
	"seguimiento_al_desembolso"	INT,
	"alerta_de_seguimiento"	INT,
	"otra_alerta"	VARCHAR(255)
);
CREATE TABLE "monitoreo" (
	"id"	VARCHAR(255) PRIMARY KEY,
	"fk_proyecto"	VARCHAR(255),
	"fk_beneficiario"	VARCHAR(255),
	"fk_operario"	VARCHAR(255),
	"numero_monitoreo"	INT,
	"total_ingresos_familia"	REAL,
	"total_gastos_familia"	REAL,
	"pertenece_a_asociacion"	INT,
	"ciiu"	INT,
	"pension"	INT,
	"sector_empresarial"	INT,
	"total_dependientes"	INT,
	"quien_define_ingresos"	INT,
	"tipo_de_casa"	INT,
	"material_de_casa"	INT,
	"numero_de_dormitorios"	INT,
	"combustible_de_cocina"	INT,
	"estrato"	INT,
	"antiguedad_de_casa"	INT,
	"cual_asociacion"	VARCHAR(255),
	"asociacion_mujeres"	INT,
	"lugar_de_basuras"	INT,
	"lavadero"	INT,
	"lavaplatos"	INT,
	"pozo_septico"	INT,
	"bano"	INT,
	"agua"	INT,
	"telefono"	INT,
	"luz"	INT,
	"internet"	INT,
	"tv_por_cable"	INT,
	"telefono_celular"	INT,
	"refrigeradora"	INT,
	"licuadora"	INT,
	"tv_a_color"	INT,
	"cuenta_corriente"	INT,
	"cuenta_de_ahorros"	INT,
	"creditos"	INT,
	"pensiones"	INT,
	"seguros"	INT,
	"numero_de_cuotas"	INT,
	"servicio_con_bancamia"	INT,
	"cual_servicio_bancamia"	INT,
	"pertenece_a_programa_publico"	INT,
	"depende_economicamente"	INT,
	"de_quien_depende"	INT,
	"cuantas_horas_dedica_a_personas"	INT,
	"cuantas_horas_dedica_recreacion"	INT,
	"tiene_rut"	INT,
	"registro_camara_comercio"	INT,
	"tiene_nit"	INT,
	"donde_opera_su_unidad"	INT,
	"trabajadores_con_contrato"	INT,
	"trabajadores_sin_contrato"	INT,
	"cantidad_de_socios"	INT,
	"tipo_de_local"	INT,
	"monte_del_credito"	REAL,
	"cual_programa"	VARCHAR(255),
	"numero_nit"	VARCHAR(255),
	"ingresos_del_negocio"	REAL,
	"gastos_directos"	REAL,
	"gastos_indirectos"	REAL,
	"total_gastos"	REAL,
	"excedentes"	REAL,
	"activo fijo"	REAL,
	"activo_no_fijo"	REAL,
	"total_activos"	REAL,
	"pasivo_corto"	REAL,
	"pasivo_largo"	REAL,
	"deudas"	REAL,
	"patrimonio"	REAL,
	"fecha"	VARCHAR(255)
);
CREATE TABLE "plan_de_implementacion" (
	"id"	VARCHAR(255) PRIMARY KEY,
	"project"	VARCHAR(255),
	"payeeDocument"	VARCHAR(255),
	"operator"	VARCHAR(255),
	"numero_de_visitas"	INT,
	"numero_realizadas"	INT,
	"meta_1"	VARCHAR(255),
	"inicio_1"	VARCHAR(255),
	"final_1"	VARCHAR(255),
	"meta_2"	VARCHAR(255),
	"inicio_2"	VARCHAR(255),
	"final_2"	VARCHAR(255),
	"meta_3"	VARCHAR(255),
	"inicio_3"	VARCHAR(255),
	"final_3"	VARCHAR(255),
	"meta_4"	VARCHAR(255),
	"inicio_4"	VARCHAR(255),
	"final_4"	VARCHAR(255),
	"meta_5"	VARCHAR(255),
	"inicio_5"	VARCHAR(255),
	"final_5"	VARCHAR(255),
	"meta_6"	VARCHAR(255),
	"inicio_6"	VARCHAR(255),
	"final_6"	VARCHAR(255),
	"meta_7"	VARCHAR(255),
	"inicio_7"	VARCHAR(255),
	"final_7"	VARCHAR(255),
	"meta_8"	VARCHAR(255),
	"inicio_8"	VARCHAR(255),
	"final_8"	VARCHAR(255),
	"meta_9"	VARCHAR(255),
	"inicio_9"	VARCHAR(255),
	"final_9"	VARCHAR(255)
);
CREATE TABLE "plan_de_formacion" (
	"id"	VARCHAR(255) PRIMARY KEY,
	"proyecto"	VARCHAR(255),
	"beneficiario"	VARCHAR(255),
	"operario"	VARCHAR(255),
	"numero_actividad"	INT,
	"id_actividad"	INT,
	"fecha_actividad"	VARCHAR(255),
	"fecha_realizada"	VARCHAR(255),
	"completada"	INT
);
CREATE TABLE "diagnostico_empresarial" (
	"id"	VARCHAR(255) PRIMARY KEY,
	"fk_proyecto"	VARCHAR(255),
	"fk_beneficiario"	VARCHAR(255),
	"fk_operario"	VARCHAR(255),
	"monitoreo"	INT,
	"categoria_1"	REAL,
	"categoria_2"	REAL,
	"categoria_3"	REAL,
	"categoria_4"	REAL,
	"categoria_5"	REAL,
	"categoria_6"	REAL,
	"categoria_7"	REAL,
	"categoria_8"	REAL,
	"categoria_9"	REAL,
	"puntaje_total"	REAL
);
CREATE TABLE "caracterizacion_ampliada_informacion_personas_a_cargo" (
	"id"	VARCHAR(255) PRIMARY KEY,
	"fkProject"	VARCHAR(255),
	"fkPayee"	VARCHAR(255),
	"fkOperator"	VARCHAR(255),
	"numero_de_persona"	INT,
	"genero"	INT,
	"mayor_de_edad"	INT,
	"discapacidad"	INT
);
CREATE TABLE "caracterizacion_ampliada_informacion_hijos" (
	"id"	VARCHAR(255) PRIMARY KEY,
	"fkProject"	VARCHAR(255),
	"fkPayee"	VARCHAR(255),
	"fkOperator"	VARCHAR(255),
	"numero_de_hijo"	INT,
	"genero"	INT,
	"mayor_de_edad"	INT,
	"discapacidad"	INT
);
CREATE TABLE "caracterizacion_ampliada" (
	"id"	VARCHAR(255) PRIMARY KEY,
	"fkProject"	VARCHAR(255),
	"fkPayee"	VARCHAR(255),
	"fkOperator"	VARCHAR(255),
	"higherEducation"	VARCHAR(255),
	"studies"	INT,
	"contractEmployment"	INT,
	"independent"	INT,
	"householdHead"	INT,
	"householdMembersQuantity"	INT,
	"healtRegime"	INT,
	"maritalStatus"	INT,
	"agreementType"	INT,
	"rut"	INT,
	"sonsQuantity"	INT,
	"dependantsQuantity"	INT,
	"coverYourFamily"	INT,
	"agreementOld"	INT,
	"averageIncomeAgreement"	INT,
	"averageIncomeActivity"	INT,
	"pension"	INT,
	"arl"	INT,
	"factorsThatStops"	VARCHAR(255),
	"observations"	VARCHAR(255)
);
CREATE TABLE "idea_de_negocio" (
	"id"	VARCHAR(255) PRIMARY KEY,
	"fkProject"	VARCHAR(255),
	"fkPayee"	VARCHAR(255),
	"fkOperator"	VARCHAR(255),
	"entrepeneurship"	VARCHAR(255),
	"bussinesSector"	INT,
	"ciiu"	INT,
	"fkDepartment"	INT,
	"fkCity"	INT,
	"howArise"	INT,
	"dedicationTime"	INT,
	"studies"	INT,
	"haveExperience"	INT,
	"productServices"	INT,
	"productServicesList"	VARCHAR(255),
	"agricultural"	INT,
	"briefcase"	VARCHAR(255),
	"assetInvestment"	REAL,
	"initialInvestment"	REAL,
	"investmentPercent"	INT,
	"capitalWorkInvestment"	REAL,
	"firstMonthSales"	REAL,
	"firstYearSales"	REAL,
	"needColabs"	INT,
	"whoColabs"	VARCHAR(255),
	"weeklyTime"	INT,
	"whyNot"	INT,
	"months"	INT,
	"imagine"	VARCHAR(255),
	"date"	VARCHAR(255)
);
CREATE TABLE "unidad_de_negocio" (
	"id"	VARCHAR(255) PRIMARY KEY,
	"project"	VARCHAR(255),
	"payeeDocument"	VARCHAR(255),
	"operator"	VARCHAR(255),
	"unit"	VARCHAR(255),
	"departments"	INT,
	"cities"	INT,
	"howManyPartners"	INT,
	"sign"	INT,
	"address"	VARCHAR(255),
	"ciiu"	INT,
	"indicator"	INT,
	"phone"	INT,
	"email"	VARCHAR(255),
	"webPage"	VARCHAR(255),
	"description"	VARCHAR(255),
	"briefcase"	VARCHAR(255),
	"creation"	REAL,
	"nit"	VARCHAR(255),
	"liabilitiesDescription"	VARCHAR(255),
	"regCamara"	INT,
	"withContract"	INT,
	"withoutContract"	INT,
	"cellphone"	INT,
	"cellphone2"	INT,
	"tier"	INT,
	"date"	VARCHAR(255)
);
CREATE TABLE "proyectos" (
	"id"	VARCHAR(255) PRIMARY KEY,
	"name"	VARCHAR(255),
	"data"	VARCHAR(255)
);
CREATE TABLE "odp_operario_proyectos" (
	"id"	VARCHAR(255) PRIMARY KEY,
	"fkOperator"	VARCHAR(255),
	"fkProject"	VARCHAR(255)
);
CREATE TABLE "diagnostico_de_perfil_productivo" (
	"payeeDocument"	VARCHAR(255) PRIMARY KEY,
	"Field1"	INT,
	"Field2"	INT,
	"Field3"	INT,
	"Field4"	INT,
	"Field5"	INT,
	"Field6"	INT,
	"Field7"	INT,
	"Field8"	INT,
	"Field9"	INT,
	"Field10"	INT,
	"Field11"	INT,
	"Field12"	INT,
	"Field13"	INT,
	"Field14"	INT,
	"Field15"	INT,
	"Field16"	INT,
	"Field17"	INT,
	"Field18"	INT,
	"Field19"	INT,
	"Field20"	INT,
	"Field21"	INT,
	"Field22"	INT,
	"Field23"	INT,
	"Field24"	INT,
	"Field25"	INT,
	"Field26"	INT,
	"Field27"	INT,
	"Field28"	INT,
	"Field29"	INT,
	"Field30"	INT,
	"Field31"	INT,
	"Field32"	INT,
	"Field33"	INT,
	"Field34"	INT,
	"Field35"	INT,
	"Field36"	INT,
	"Field37"	INT,
	"Field38"	INT,
	"Field39"	INT,
	"Field40"	INT,
	"Field41"	INT,
	"Field42"	INT,
	"Field43"	INT,
	"Field44"	INT,
	"Field45"	INT,
	"Field46"	INT,
	"Field47"	INT,
	"Field48"	INT,
	"Field49"	INT,
	"Field50"	INT,
	"Field51"	INT,
	"Field52"	INT,
	"Field53"	INT,
	"Field54"	INT,
	"Field55"	INT,
	"Field56"	INT,
	"Field57"	INT,
	"Field58"	INT,
	"Field59"	INT,
	"Field60"	INT,
	"Field61"	INT,
	"Field62"	INT,
	"Field63"	INT,
	"Field64"	INT,
	"Field65"	INT,
	"Field66"	INT,
	"Field67"	INT,
	"Field68"	INT,
	"Field69"	INT,
	"Field70"	INT
);
CREATE TABLE "informacion_general_beneficiario" (
	"project"	VARCHAR(255),
	"names"	VARCHAR(255),
	"lastNames"	VARCHAR(255),
	"docType"	INT,
	"document"	VARCHAR(255) PRIMARY KEY,
	"expeditionCity"	INT,
	"birthdate"	VARCHAR(255),
	"city"	INT,
	"department"	INT,
	"country"	INT,
	"sign"	INT,
	"address"	VARCHAR(255),
	"neighborhood"	INT,
	"indicative"	INT,
	"telephone"	INT,
	"cellphone"	INT,
	"email"	VARCHAR(255),
	"operator"	VARCHAR(255),
	"cellphone2"	INT,
	"payeeType"	INT,
	"date"	VARCHAR(255),
	"ageRange"	INT,
	"nationality"	INT,
	"environment"	INT,
	"tier"	INT,
	"sex"	INT,
	"gender"	INT,
	"ethnicGroup"	INT,
	"disability"	INT
);
CREATE TABLE "odp_operario" (
	"document"	VARCHAR(255) PRIMARY KEY,
	"name"	VARCHAR(255),
	"username"	VARCHAR(255),
	"password"	VARCHAR(255),
	"type"	INT
);

